# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs: 
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: python3 circleCI_test.py
workflows:
  main:
    jobs:
      - build-and-test
deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://git.heroku.com/classroom-creator.git master
